server:
  port: 8888

spring:
  application:
    name: movies-config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/aindytskyi/Documents/SpringWebFlux/reactive-spring-webFlux/spring-webFlux/movies-config-service/src/main/resources/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
