server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/aindytskyi/Documents/SpringWebFlux/reactive-spring-webFlux/reactive-spring-webFlux/movies-config-service/src/main/resources/config
