server:
  port: 8082

spring:
  data:
    mongodb:
      username: root
      password: password
      host: localhost
      port: 27017
      database: reactivespring
      authentication-database: admin

