spring:
  application:
    name: movies-service
  config:
    activate:
      on-profile: -local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

